name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -o pomo main.go
        mv pomo pomo-linux-amd64
        GOOS=darwin GOARCH=amd64 go build -o pomo main.go
        mv pomo pomo-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o pomo main.go
        mv pomo pomo-darwin-arm64
        GOOS=windows GOARCH=amd64 go build -o pomo.exe main.go
        mv pomo.exe pomo-windows-amd64.exe
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          pomo-linux-amd64
          pomo-darwin-amd64
          pomo-darwin-arm64
          pomo-windows-amd64.exe
        generate_release_notes: true
